<a href="https://colab.research.google.com/github/Gr3gP/Misc-Projects/blob/main/Numpy_and_Pytorch_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
@article{madewithml,
    title  = "PyTorch - Made With ML",
    author = "Goku Mohandas",
    url    = "https://madewithml.com/courses/basics/pytorch/"
    year   = "2021",
}

#Numpy

How to create vectors and tensors in Numpy

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/tensors.png" width="650">
</div>

In [1]:
import numpy as np

In [4]:
#Scaler 
x = np.array(6)
print('x: ', x)
print('x ndim:', x.ndim)
print('x shape: ', x.shape)
print('x size: ', x.size)
print('x dtype: ', x.dtype)

x:  6
x ndim: 0
x shape:  ()
x size:  1
x dtype:  int64


In [5]:
#vector
x = np.array([1.3, 2.2, 1.7])
print('x:\n', x)
print('x ndim:', x.ndim)
print('x shape: ', x.shape)
print('x size: ', x.size)
print('x dtype: ', x.dtype)

x:
 [1.3 2.2 1.7]
x ndim: 1
x shape:  (3,)
x size:  3
x dtype:  float64


In [7]:
#Matrix
x = np.array([[1,2], [3,4]])
print('x: ', x)
print('x ndim:', x.ndim)
print('x shape: ', x.shape)
print('x size: ', x.size)
print('x dtype: ', x.dtype)

x:  [[1 2]
 [3 4]]
x ndim: 2
x shape:  (2, 2)
x size:  4
x dtype:  int64


In [12]:
#3-D tensor
x = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
print('x: ', x)
print('x ndim:', x.ndim)
print('x shape: ', x.shape)
print('x size: ', x.size)
print('x dtype: ', x.dtype)

x:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim: 3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [13]:
#numpy functions to create tensors quickly
print('np.zeros((2,2)):\n', np.zeros((2,2)))
print('np.ones((2,2)):\n', np.ones((2,2)))
print('np.eye((2)):\n', np.eye((2))) #idenntity matrix
print('np.random.random((2,2)):\n', np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.26291965 0.8465587 ]
 [0.48286829 0.23235895]]


<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/indexing.png" width="300">
</div>

In [14]:
#we can pull exaxt values from matrixes by indexing
x = np.array([1,2,3])
print('x: ', x)
print('x[0]: ', x[0])
x[0] = 0
print('x: ', x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [15]:
#slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print('x column:', x[:, 1])
print('x row 0: ', x[0, :])
print('x rows 0,1 and cols 1,2: \n', x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column: [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 and cols 1,2: 
 [[2 3]
 [6 7]]


In [16]:
#integer array indexing 
print(x)
rows_to_get = np.array([0,1,2])
print('rows_to_get: ', rows_to_get)
cols_to_get = np.array([0,2,1])
print('cols_to_get: ', cols_to_get)
#combine sequences above to get values to get
print ('indexed values: ', x[rows_to_get, cols_to_get])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [17]:
#coolean array indexing
x = np.array([[1,2], [3,4], [5,6]])
print('x:\n', x)
print('x > 2:\n', x > 2)
print('x[x>2]:\n', x[x>2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x>2]:
 [3 4 5 6]


##Arithmetic

In [19]:
#basics
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print('x+y:\n', np.add(x,y))
print('x-y:\n', np.subtract(x, y))
print('x * y:\n', np.multiply(x,y))
print('x / y:\n', np.divide(x,y))

x+y:
 [[2. 4.]
 [6. 8.]]
x-y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]
x / y:
 [[1. 1.]
 [1. 1.]]


##Dot Product

One of the most common NumPy operations we’ll use in machine learning is matrix multiplication using the dot product. We take the rows of our first matrix (2) and the columns of our second matrix (2) to determine the dot product, giving us an output of `[2 X 2]`. The only requirement is that the inside dimensions match, in this case the first matrix has 3 columns and the second matrix has 3 rows. 

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/dot.gif" width="450">
</div>

In [20]:
#dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64)
b = np.array([[7,8], [9,10], [11,12]], dtype=np.float64)
c = a.dot(b)
print(f'{a.shape} · {b.shape} = {c.shape}')
print(c)

(2, 3) · (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


## Axis operations

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/axis.gif" width="450">
</div>

In [22]:
#sum across a dimension
x = np.array([[1,2], [3,4]])
print(x)
print('sum all: ', np.sum(x)) #sum all elements
print('sum axis=0: ',np.sum(x, axis=0)) #sum across rows
print('sum axis=1: ', np.sum(x, axis=1)) #sum across cols

[[1 2]
 [3 4]]
sum all:  10
sum axis=0:  [4 6]
sum axis=1:  [3 7]


In [24]:
#min/max
x = np.array([[1,2,3], [4,5,6]])
print('min: ', x.min())
print('max: ', x.max())
print('min axis=0: ', x.min(axis=0))
print('min axis=1: ', x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


##Broadcasting

Broadcasting helps us combine values wiht different dims. Like below, a scaler(3) and a vector([1,2]) are combined by broadcastin 3 from a scaler to a vector.



<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/broadcast.png" width="300">
</div>

In [25]:
#broadcasting
x = np.array([1,2]) #vector
y = np.array(3) #scaler
z = x + y
print('z:\n', z)

z:
 [4 5]


##Transpose

We can change the dims of our tensors for operations like dot product.If we need to switch to two dims, we can transpose the tensor.

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/transpose.png" width="400">
</div>

In [27]:
#transpose
x = np.array([[1,2,3], [4,5,6]])
print('x:\n', x)
print('x.shape: ', x.shape)
y = np.transpose(x, (1,0)) #flip dims at 0 and 1
print('y:\n', y)
print('y.shape: ', y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y:
 [[1 4]
 [2 5]
 [3 6]]
y.shape:  (3, 2)


##Reshape

We will sometimes want to reshape a tensor. It will have to have  the same number of elements(1X6=2X3) but the possiblities are vast. 



<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/reshape.png" width="450">
</div>

In [28]:
#reshaping
x = np.array([[1,2,3,4,5,6]])
print(x)
print('x.shape: ', x.shape)
y = np.reshape(x, (2,3))
print(y)
print('y.shape: ', y.shape)
z = np.reshape(x, (2, -1))
print(z)
print('z.shape: ', z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
[[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
[[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


##Reshaping Pitfalls

Below we see an unintended reshape. 

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/reshape_wrong.png" width="600">
</div>

In [29]:
x = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
              [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)

x:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
x.shape:  (2, 3, 4)


In [31]:
#unintended rehsape
z_incorrect = np.reshape(x, (x.shape[1], -1))
print('z_incorrect: \n', z_incorrect)
print('z_incorrect.shape: ', z_incorrect.shape)

z_incorrect: 
 [[ 1  1  1  1  2  2  2  2]
 [ 3  3  3  3 10 10 10 10]
 [20 20 20 20 30 30 30 30]]
z_incorrect.shape:  (3, 8)


Instead, we can transpose and then reshape our tensor to get the desired outcome. Transpose lets us put our two vectors we want to combine together and then we use reshape to join them.

> Dummy variables are very helpful when unsure about reshaping.



<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/basics/numpy/reshape_right.png" width="600">
</div>

In [32]:
#intended reshape
y = np.transpose(x, (1,0,2))
print( 'y:\n', y)
print('y.shape: ', y.shape)
z_correct = np.reshape(y, (y.shape[0], -1))
print('z_correct: ', z_correct)
print('z_correct.shape: ', z_correct.shape)

y:
 [[[ 1  1  1  1]
  [10 10 10 10]]

 [[ 2  2  2  2]
  [20 20 20 20]]

 [[ 3  3  3  3]
  [30 30 30 30]]]
y.shape:  (3, 2, 4)
z_correct:  [[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]
z_correct.shape:  (3, 8)


##Expanding and Reducing

We can also easily add and remove dimensions to our tensors. We will do this to make tensors compatible for certain operations.

In [33]:
#Adding dimensions
x = np.array([[1,2,3], [4,5,6]])
print('x:\n', x)
print('x.shape', x.shape)
y = np.expand_dims(x,1) #expand dim 1
print('y:\n', y)
print('y.shape: ', y.shape)

x:
 [[1 2 3]
 [4 5 6]]
x.shape (2, 3)
y:
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [36]:
#remove dimensions
x = np.array([[[1,2,3]], [[4,5,6]]])
print('x:\n', x)
print('s.shape: ', x.shape)
y = np.squeeze(x, 1) #squeeze dim 1
print('y:\n', y)
print('y.shape: ', y.shape) #notice extra set of brackets

x:
 [[[1 2 3]]

 [[4 5 6]]]
s.shape:  (2, 1, 3)
y:
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


#Pytorch

In [37]:
import numpy as np
import torch

In [38]:
SEED = 1234

In [39]:
#set seeds
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

##Basics

In [41]:
#create random tensor
x = torch.randn(2,3)
print(f'Type: {x.type()}')
print(f'Size: {x.shape}')
print(f'Values: \n{x}')

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [42]:
#zeros and ones tensor
x = torch.zeros(2, 3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [44]:
#List -> Tensor
x = torch.Tensor([[1,2,3],[4,5,6]])
print(f'Size: {x.shape}')
print(f'Values: \n{x}')

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [45]:
#Cahange tensor type
x = torch.Tensor(3,4)
print(f'Type: {x.type()}')
x = x.long()
print(f'Type: {x.type()}')

Type: torch.FloatTensor
Type: torch.LongTensor


##Operations

In [47]:
#addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x + y
print(f'Size: {z.shape}')
print(f'Values: {z}')

Size: torch.Size([2, 3])
Values: tensor([[ 0.1824, -1.3555, -1.0664],
        [ 1.0333,  0.1368, -0.1310]])


In [49]:
#Dot product
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y)
print(f'Size: {z.shape}')
print(f'Values: {z}')

Size: torch.Size([2, 2])
Values: tensor([[ 0.4173,  0.2528],
        [-3.6668, -1.6944]])


In [50]:
#Transpose
x = torch.randn(2,3)
print(f'Size: {x.shape}')
print(f'Values: \n{x}')
y = torch.t(x)
print(f'Size: {y.shape}')
print(f'Values: \n{y}')

Size: torch.Size([2, 3])
Values: 
tensor([[-0.2349, -0.0306,  1.7462],
        [-0.0722, -1.6794, -1.7010]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.2349, -0.0722],
        [-0.0306, -1.6794],
        [ 1.7462, -1.7010]])


In [51]:
#Reshape
x = torch.randn(2,3)
z = x.view(3,2)
print(f'Size: {z.shape}')
print(f'Values: \n{z}')

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.6486,  1.7653],
        [ 1.0812,  1.2436],
        [ 0.8971, -0.0784]])


In [54]:
#dangers of reshaping
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])

print(f'size: {x.shape}')
print(f'x: \n{x}\n')

a = x.view(x.size(1), -1)
print(f'\nSize: {a.shape}')
print(f'a: \n{a}\n')

b = x.transpose(0,1).contiguous()
print(f'\nSize: {b.shape}')
print(f'b: \n{b}\n')

c = b.view(b.size(0), -1)
print(f'\nSize: {c.shape}')
print(f'c: \n{c}')

size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [56]:
#dimensional operations
x = torch.randn(2,3)
print(f'Values: \n{x}')
y = torch.sum(x, dim=0) #add each row's values for every col
print(f'Values: \n{y}')
z = torch.sum(x, dim=1) #add each col's value for every row
print(f'Values: \n{z}')

Values: 
tensor([[ 0.8246, -0.5723, -0.4876],
        [ 0.1944, -1.0481, -0.0741]])
Values: 
tensor([ 1.0190, -1.6204, -0.5617])
Values: 
tensor([-0.2353, -0.9278])


##Indexing, Splicing, and Joining

In [58]:
x = torch.randn(3,4)
print(f'x: \n{x}')
print(f'x[:1]: \n{x[:1]}') #returns the first row of the tensor
print(f'x[:1, 1:3]: \n{x[:1, 1:3]}') #returns the first row, first and second elements

x: 
tensor([[-0.4572,  0.0901,  0.4018, -1.1542],
        [ 0.1192, -0.7348, -1.5864, -0.2671],
        [ 2.6874, -0.4633,  0.6639,  0.2383]])
x[:1]: 
tensor([[-0.4572,  0.0901,  0.4018, -1.1542]])
x[:1, 1:3]: 
tensor([[0.0901, 0.4018]])


In [59]:
#select dimensional indices
x = torch.randn(2,3)
print(f'Values: \n{x}')

col_indices = torch.LongTensor([0,2])
chosen = torch.index_select(x, dim=1, index=col_indices) #values from col 0&2
print(f'Values: \n{chosen}')

row_indices = torch.LongTensor([0,1])
col_indices = torch.LongTensor([0,2])
chosen = x[row_indices, col_indices] #values from (0,0) & (2,1)
print(f'Values: \n{chosen}')

Values: 
tensor([[ 0.8305, -0.0838,  0.9523],
        [ 0.2016, -0.1714, -0.8164]])
Values: 
tensor([[ 0.8305,  0.9523],
        [ 0.2016, -0.8164]])
Values: 
tensor([ 0.8305, -0.8164])


In [60]:
x = torch.randn(2,3)
print(f'Values: \n{x}')
y = torch.cat([x, x], dim=0) #stack by rows
print(f'Values: \n{y}')

Values: 
tensor([[-0.6066, -0.4800,  1.1733],
        [ 0.3714, -2.3531, -1.6705]])
Values: 
tensor([[-0.6066, -0.4800,  1.1733],
        [ 0.3714, -2.3531, -1.6705],
        [-0.6066, -0.4800,  1.1733],
        [ 0.3714, -2.3531, -1.6705]])


#Gradients

* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(y)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

In [61]:
#Tensors with gradient bookkeeping
x = torch.rand(3,4, requires_grad=True)
y = 3*x +2
z = y.mean()
z.backward() #z has to be scaler
print(f'x: \n{x}')
print(f'x.grad: \n{x.grad}')

x: 
tensor([[0.0417, 0.0214, 0.6696, 0.0336],
        [0.0903, 0.7542, 0.7427, 0.0444],
        [0.8598, 0.4028, 0.8712, 0.2066]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


##CUDA tensors

In [62]:
#IS CUDA available
print(torch.cuda.is_available())

False


If False (CUDA is not available), let's change that by following these steps: Go to Runtime > Change runtime type > Change Hardware accelertor to GPU > Click Save



In [1]:
import torch

In [2]:
#Is CUDA available now
print(torch.cuda.is_available())

True


In [4]:
#set device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [6]:
x = torch.rand(2,3)
print(x.is_cuda)
x = torch.rand(2,3).to(device) #stensor is sorted on the GPU
print(x.is_cuda)

False
True
